---
title: "Snowflake Demand Scripts"
author: "Payman Alemi"
date: '`r Sys.Date()`'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## DEMAND_DATA_FLAGS Schema

As of 2/12/2025, all the SQL scripts, tables, and views for the SDA Unit's demand data and scripts are housed under the **DEMAND_DATA_FLAGS** schema within the DWR_DEV database on the Water Boards Snowflake server. The purpose of this document is to describe the purpose and functions of the individual SQL scripts, tables, vies, and tasks that live here.

## VIEWS

* **EWRIMS_FLAT_FILE_POD**
* **EWRIMS_FLAT_FILE_WATER_USE_REPORT_EXTENDED**
* **VW_POD_FLAT_FILE**
* **VW_WATER_USE_REPORT_EXTENDED**

## TABLES

* **POD_FLAT_FILE_ACTIVE**
* **WATER_USE_REPORT_EXTENDED**

## TASKS

* **CREATE_POD_FLAT_FILE_ACTIVE**

Payman created this task to call the stored procedure *Create_POD_Flat_File_Active* on a daily schedule, but unfortunately the task will not run due to insufificient permissions. The intent of this stored procedure was to  update the POD_FILE_ACTIVE_TABLe daily.

* **CREATE_WATER_USE_REPORT_EXTENDED_TABLE**



